# Generated by Django 5.2.8 on 2025-11-20 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tcomentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario', models.CharField(blank=True, max_length=2000, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tComentarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tlibros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('url_imagen', models.CharField(blank=True, max_length=200, null=True)),
                ('autor', models.CharField(blank=True, max_length=100, null=True)),
                ('año_publicacion', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'tLibros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tusuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('apellidos', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.CharField(blank=True, max_length=200, null=True, unique=True)),
                ('contraseña', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'tUsuarios',
                'managed': False,
            },
        ),
    ]
