# Generated by Django 6.0 on 2026-01-20 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('stock', models.IntegerField()),
                ('requiere_receta', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'medicamento',
                'verbose_name_plural': 'medicamentos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('fecha_nacimiento', models.DateField()),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'paciente',
                'verbose_name_plural': 'pacientes',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alergias', models.CharField(blank=True, max_length=255)),
                ('enfermedades_cronicas', models.CharField(blank=True, max_length=255)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='farmacia.paciente')),
            ],
            options={
                'verbose_name': 'historial médico',
                'verbose_name_plural': 'historiales médicos',
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('medico', models.CharField(max_length=120)),
                ('observaciones', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='farmacia.paciente')),
            ],
            options={
                'verbose_name': 'receta',
                'verbose_name_plural': 'recetas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='RecetaMedicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosis', models.CharField(max_length=50)),
                ('frecuencia', models.CharField(max_length=50)),
                ('duracion_dias', models.IntegerField()),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=8)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='farmacia.medicamento')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='farmacia.receta')),
            ],
            options={
                'verbose_name': 'medicamento en receta',
                'verbose_name_plural': 'medicamentos en receta',
                'ordering': ['receta', 'id'],
                'constraints': [models.UniqueConstraint(fields=('receta', 'medicamento'), name='unique_medicamento_por_receta')],
            },
        ),
    ]
